version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:14.7
    steps: 
      - checkout
      - restore_cache:
          key: npm-deps{{checksum "package-lock.json"}}
      - run: npm install
      - save_cache:
          key: npm-deps{{checksum "package-lock.json"}}
          paths:
            - ./node_modules
  build_docker:
    environment:
      IMAGE_NAME: sgttabouret/facebok
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run: 
          name: building image
          command: docker image build --tag $IMAGE_NAME:app .
      - run:
          name: saving image
          command: docker save -o image.tar $IMAGE_NAME
      - persist_to_workspace:
          root: .
          paths:
            - ./image.tar
  docker_push:
    environment:
      IMAGE_NAME: sgttabouret/facebok
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run: docker load -i /tmp/workspace/image.tar
      - run:
          name: Login and push to DockerHub
          command: |
            echo "$DOCKERHUB_PASS" | docker login --username sgttabouret --password-stdin
            docker tag $IMAGE_NAME:app $IMAGE_NAME:$CIRCLE_BUILD_NUM
            docker tag $IMAGE_NAME:app $IMAGE_NAME:latest
            docker push $IMAGE_NAME:$CIRCLE_BUILD_NUM
            docker push $IMAGE_NAME:latest
  
workflows:
  build-and-push:
    jobs:
      - build
          filters:
              branches:
                only:
                  - master
      - build_docker:
          requires: 
            - build
      - docker_push:
          requires: 
            - build_docker
          context:
            - DOCKER
