version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:14.7
    steps: 
      - checkout
      - restore_cache:
        key: npm-deps{{checksum "package-lock.json"}}
      - run: npm install
      - save_cache:
        key: npm-deps{{checksum "package-lock.json"}}
        paths:
          - ./node_modules

workflows:
  build-and-push:
    jobs:
      - build